homeassistant:
  name: Geral
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 17
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
config:

frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html


############
# INCLUDES #
############

group: !include groups.yaml
sensor: !include sensor.yaml
device_tracker: !include device_tracker.yaml
tts: !include googletts.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
input_select: !include input_select.yaml
script: !include script.yaml
proximity: !include proximity.yaml
history_graph: !include history_graph.yaml



xiaomi_aqara:
  discovery_retry: 5
  gateways:   
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key
      host: 192.168.1.79

    

map:
discovery:
sun:
conversation:
logger:
  default: debug
recorder:
history:
#logbook:



  
http:
  base_url: !secret meu_dns
  api_password: !secret api_password_http
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3
  
panel_iframe:
  ide:
    title: IDE
    icon: mdi:wrench
    url: !secret url_panel
  
  

