- platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  language: 'pt'
  
- platform: microsoft
  api_key: !secret api_key_tts
  language: pt-pt
  gender: Female
  type: HeliaRUS
  rate: -10
  volume: 40
  
- platform: voicerss
  api_key: !secret api_key_voicerss
  language: 'pt-pt'
  codec: mp3
  format: '44khz_16bit_stereo'
  
  
