- platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300
  language: 'pt'

  
- platform: voicerss
  api_key: !secret api_key_voicerss
  language: 'pt-pt'
  codec: mp3
  format: '44khz_16bit_stereo'
  
  
