homeassistant:  
  customize:
    switch.regar_plantas_varanda:
      icon: mdi:flower
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:
#Rega as Plantas nos dias definidos e informa a dona da casa que a rega foi feita com sucesso. Automação Nº 14
  - alias: Regar Plantas
    trigger:
      - platform: time
        at: '18:20:00'
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
          - sun
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.regar_plantas_varanda
      - delay: 00:01:00
      - service: switch.turn_off
        data:
          entity_id: switch.regar_plantas_varanda
###############################################################################
#                                                                             #
#                           S C R I P T S                                     #
#                                                                             #
###############################################################################  
#Não existem scripts para as automações acima referidas.
###############################################################################
#                                                                             #
#                           S W I T C H E S                                   #
#                                                                             #
###############################################################################  
switch:
#Switch Nº 4  
  - platform: mqtt
    name: "Regar Plantas Varanda"
    state_topic: "stat/sonoff1/POWER"
    command_topic: "cmnd/sonoff1/power"
    qos: 1
    payload_on: "1"
    payload_off: "0"
    retain: true
    
###############################################################################
#                                                                             #
#                         BINARY SENSORS                                      #
#                                                                             #
###############################################################################      
    
binary_sensor:
  - platform: mqtt
    name: "Sonoff Plantas Varanda"
    state_topic: "tele/sonoff1/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
###############################################################################
#                                                                             #
#                           G R O U P S                                       #
#                                                                             #
###############################################################################  
group:
  plantas:
    name: Plantas
    entities:
      - switch.regar_plantas_varanda