homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
        
#  customize:

       


switch:

        
  - platform: broadlink
    host: 192.168.1.111
    mac: '34:ea:34:58:8a:2a'
    switches:
      boxbia: 
        friendly_name: 'boxbia'
        command_on: 'JgBOAAoVFRUUFRQLChUVFQkLCwsUFRQKCxUJAAtoChUVFBUVFAsKFRUVCQsLCxMVFQoLFQkAC2gKFRQVFRUUCgsVFBULCgkMFBUVCgsUCgANBQAAAAAAAAAAAAA=' 
        command_off: 'JgBOAAoVFRUUFRQLChUVFQkLCwsUFRQKCxUJAAtoChUVFBUVFAsKFRUVCQsLCxMVFQoLFQkAC2gKFRQVFRUUCgsVFBULCgkMFBUVCgsUCgANBQAAAAAAAAAAAAA=' 
      desligaacbia:
        friendly_name: 'Ar Condicionado Bia'
        command_off: 'JgC8AXE5DioPDg0PDQ8OKw0PDg4ODw0PDSsODw0rDisNDw0sDSsOKw0rDisNDwwQDSwMEA0QDBAMEAwQDRAMLAwtDSsOKwwQDBANEAwQDBANEAwQDBAMEA0QDBAMEAwQDRAMEAwQDRAMEAwQDBANEAwQDBAMEA4PDSsODw0PDQ8ODg4PDQ8NAAPNcjgOKg8ODg4ODg8qDg4PDQ8NDw4OKg8ODioPKg4ODykPKg8pDyoPKg4ODw0PKg4ODw0PDg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw0PDg4ODw0PDg4ODg4PDQ8qDw0PDQ8ODioPKg4ODyoODg8NDw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8ODg4OKg8ODioPDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8ODg4ODg8NDw4ODg8NDw0PDg4ODw0PDg4ODg4PDQ8ODg4PDQ8NDw4ODg8NDw4ODg4ODw0PDg4ODg4PDQ8ODg4PKg4qDw0PDg4ODg4PDg4ODg4ODg8ODg4NDw4ODg8NDw0PDg8NDw0rDisNKw4rDg4OKw0rDgANBQAAAAAAAAAAAAAAAA=='
        
        

  - platform: mqtt
    name: "Interruptor Quarto Bia"
    state_topic: "stat/sonoffquartobia/POWER"
    command_topic: "cmnd/sonoffquartobia/power"
    availability_topic: "tele/sonoffquartobia/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Candeiro Cama Bia"
    state_topic: "stat/candeirobia/POWER"
    command_topic: "cmnd/candeirobia/power"
    availability_topic: "tele/candeirobia/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true    
        
        
        
climate:
  - platform: broadlink
    name: Ar Condicionado Bia
    host: 192.168.1.111
    mac: '34:ea:34:58:8a:2a'
    ircodes_ini: 'broadlink_climate_codes/daikin.ini'
    min_temp: 10
    max_temp: 30
    target_temp: 20
#    temp_sensor: sensor.living_room_temperature
    default_operation: idle
    default_fan_mode: mid
    customize:
      operations:
        - idle
        - cool
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
                             
###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      
        
    

input_boolean:
  ac_bia_off:
    name: Desligar Ac Bia
    icon: mdi:air-conditioner
    initial: off
    
  box_bia:
    name: Box Bia
    icon: mdi:television-classic
    initial: off
    
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################     
automation:    

#Automação para desligar o candeiro da bia durante a madrugada quando ele está ligado por mais que 10 min.

  - alias: Desligar candeiro da Bia
    trigger:
      - platform: state
        entity_id: switch.candeiro_cama_bia
        to: 'on'
        for:
          minutes: 10
    condition:
      condition: time
      after: '23:00'
      before: '08:00'
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.candeiro_cama_bia
         
#Quando carregado o botao do input_boolean o ac é desligado.
  - alias: Desliga Ac quarto Bia
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.ac_bia_off
      to: "off"
    action:
     - service: climate.set_operation_mode
       data:
         entity_id: climate.ar_condicionado_bia
         operation_mode: "idle"
         
         
#Automação para activar o botão do input_boolean assim que o ac é ligado.        
  - alias: Automação botao off
    initial_state: true
    trigger:
      platform: template
      value_template: >
          {%- if is_state("climate.ar_condicionado_bia", "idle") -%}
            false
           {% else %}
             true
          {% endif %}
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ac_bia_off
        

#Automação para ligar a tv quando a box é ligada.      
  - alias: Automação box on tv on
    initial_state: true
    trigger:
      platform: template
      value_template: >
          {%- if is_state("media_player.box_quarto_bia", "playing") -%}
            true
          {% endif %}
    action:
      - delay:
          seconds: 3
      - service: switch.broadlink_send_packet_192_168_1_111
        data:
         packet:
         - 'JgCEAFceDh0ODw4PDh0eDg4PDg8ODw4PDg8ODg8ODw4PDg8ODw4dDg8dDg8OAAq9WB0OHQ8ODg8OHh0ODg8PDg4PDg8ODw4PDg8ODw4ODw4PDh0PDh0ODw4ACr5XHQ8cDw4PDg8dHQ4PDg8ODw4PDg8ODw4PDg4PDg8ODw4PHQ4PHA8ODwANBQAAAAA='        
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.box_bia 
    
        

#Automação para desligar a tv quando a box é desligada.      
  - alias: Automação box off tv off
    initial_state: true
    trigger:
      platform: template
      value_template: >
          {%- if is_state("media_player.box_quarto_bia", "standby") -%}
            true
          {% endif %}
    action:
      - delay:
          seconds: 5
      - service: switch.broadlink_send_packet_192_168_1_111
        data:
          packet:
          - 'JgCEAFceDh0ODw4PDh0eDg4PDg8ODw4PDg8ODg8ODw4PDg8ODw4dDg8dDg8OAAq9WB0OHQ8ODg8OHh0ODg8PDg4PDg8ODw4PDg8ODw4ODw4PDh0PDh0ODw4ACr5XHQ8cDw4PDg8dHQ4PDg8ODw4PDg8ODw4PDg4PDg8ODw4PHQ4PHA8ODwANBQAAAAA='
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.box_bia   

          

#Automação para ligar a box e tv quando o botao input_boolean é activo.     
  - alias: Automação para ligar e tv botao activo
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.box_bia
      from: "off"
      to: "on"
    condition:
      condition: template
      value_template: "{{states.media_player.box_quarto_bia.state == 'standby'}}"
    action:      
      - service: homeassistant.turn_on
        data:
          entity_id: media_player.box_quarto_bia  

##Automação para desligar a box e tv quando o botao input_boolean é desactivo.     
  - alias: Automação para ligar e tv botao desactivo
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.box_bia
      from: "on"
      to: "off"
    condition:
      condition: template
      value_template: "{{states.media_player.box_quarto_bia.state == 'playing'}}"
    action:      
      - service: homeassistant.turn_off
        data:
          entity_id: media_player.box_quarto_bia  
          
##Ligar Tv bia às 07:35
  - alias: ligar tv bia de manha
    trigger:
      platform: time
      at: '07:35:00'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: media_player.box_quarto_bia 
        
###############################################################################
#                                                                             #
#                           B I N A R Y   S E N S O R S                       #
#                                                                             #
###############################################################################         
        
binary_sensor:

  - platform: device_tracker_sensor
    entities:
      - device_tracker.broadlinkquartobia
      - device_tracker.boxquartobia
      
  - platform: mqtt
    name: "Sonoff Interruptor Quarto Bia"
    state_topic: "tele/sonoffquartobia/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    
  - platform: mqtt
    name: "Sonoff Candeiro Cama Bia"
    state_topic: "tele/candeirobia/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
      
      
 
      
###############################################################################
#                                                                             #
#                           G R O U P                                         #
#                                                                             #
###############################################################################       
      
group:
  
  quartobia:
    view: yes
    name: QUARTO BIA
    entities:
      - group.quartobiagroup

  quartobiagroup:
    control: hidden
    name: Quarto Bia
    entities:
      - switch.interruptor_quarto_bia
      - switch.candeiro_cama_bia
      - input_boolean.box_bia
      - climate.ar_condicionado_bia
      - input_boolean.ac_bia_off
      

      
###############################################################################
#                                                                             #
#                           S W I T C H E S                                   #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                           M E D I A _  P L A Y E R S                        #
#                                                                             #
###############################################################################  
  

media_player:

  - platform: mediaroom

#    optimistic: True