homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
        
  customize:
 
    switch.candeiro_sofa:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true 
      confirm_controls_show_lock: false
      icon: mdi:lightbulb-outline 
    sensor.tvsala:
      icon: mdi:desktop-mac
    
###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      
        
    

input_boolean:
   
  box_sala:
    name: Box Sala
    icon: mdi:television-classic
    initial: off      
      
     

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:
#Liga o Candeiro ao lado do sofá às 17:30.
  - alias: Liga Candeiro
    trigger:
      platform: time
      at: '19:30:00'
    action:
      service: switch.turn_on
      data:
        entity_id: switch.candeiro_sofa

#Desliga o Candeiro ao lado do sofá às 04:30. 
  - alias: Desliga Candeiro
    trigger:
      platform: time
      at: '04:30'
    action:
      service: switch.turn_off
      data:
        entity_id: switch.candeiro_sofa

#Automação para ligar box quando a tv é ligada.      
  - alias: Automação box sala on tv on
    initial_state: true
    trigger:
      platform: template
      value_template: >
          {%- if is_state("media_player.panasonic_viera_tv", "on") -%}
            true
          {% endif %}
    action:
      - delay:
          seconds: 3
      - service: switch.broadlink_send_packet_192_168_1_100
        data:
         packet:
         - 'JgBoAAoVFBUUFhQLCxQVFAsKCwoVFBULChUKAAtqChUUFRUVFAsKFRQVCwoLCxMVFQsKFQoAC2oLFBQVFRUUCwsUFRUKCgsKFRUUCwoVCwALaQsUFRQVFRQLCxQUFgoKCwoUFhULCRULAA0F'        
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.box_sala

#Automação para desligar a box quando a tv é desligada.      
  - alias: Automação box sala off tv off
    initial_state: true
    trigger:
      platform: template
      value_template: >
          {%- if is_state("media_player.panasonic_viera_tv", "off") -%}
            true
          {% endif %}
    action:
      - delay:
          seconds: 5
      - service: switch.broadlink_send_packet_192_168_1_100
        data:
          packet:
          - 'JgBoAAoVFBUUFhQLCxQVFAsKCwoVFBULChUKAAtqChUUFRUVFAsKFRQVCwoLCxMVFQsKFQoAC2oLFBQVFRUUCwsUFRUKCgsKFRUUCwoVCwALaQsUFRQVFRQLCxQUFgoKCwoUFhULCRULAA0F'
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.box_sala  

          

#Automação para ligar a tv quando o botao input_boolean é activo.     
  - alias: Automação para ligar tv sala botao activo
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.box_sala
      from: "off"
      to: "on"
    condition:
      condition: template
      value_template: "{{states.media_player.panasonic_viera_tv.state == 'off'}}"
    action:      
      - service: switch.broadlink_send_packet_192_168_1_100
        data:
          packet:
          - 'JgAyAXE6Dw4OKw8ODg8NDw4PDg8NDw4PDg4ODw8ODQ8OLA4ODg8ODw0PDg8ODw0PDw4ODw0sDg8ODg4PDQ8ODw4PDQ8ODw8qDw4OKw8rDisOKw4PDg8OKw4ODiwNLA8qDysODg8rDQAJm3I5Dw4PKg8ODg8ODg4PDg8NDw4PDg8NDw8ODg8OKw4ODg8PDg0QDQ8ODw4ODg8ODw4rDg8ODg4PDg8NDw4PDg8NDw8qDw4PKg8rDisPKg4PDw4NLA4PDisOKw8qDysODg4sDgAJm3E6Dw4OKw8ODg8NDw8ODRAODg4PDg4PDg8ODQ8OLA0PDg8ODw4ODg8ODw0PDg8ODw0sDg8NDw4PDQ8ODw4PDg4ODw8qDw4OKw4sDisOKw8ODg8NLA4ODysOKw4rDysODg8rDgANBQAAAAAAAA=='

##Automação para desligar a tv quando o botao input_boolean é desactivo.     
  - alias: Automação para desligar e tv sala botao desactivo
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.box_sala
      from: "on"
      to: "off"
    condition:
      condition: template
      value_template: "{{states.media_player.panasonic_viera_tv.state == 'on'}}"
    action:      
      - service: switch.broadlink_send_packet_192_168_1_100
        data:
          packet:
          - 'JgAyAXE6Dw4OKw8ODg8NDw4PDg8NDw4PDg4ODw8ODQ8OLA4ODg8ODw0PDg8ODw0PDw4ODw0sDg8ODg4PDQ8ODw4PDQ8ODw8qDw4OKw8rDisOKw4PDg8OKw4ODiwNLA8qDysODg8rDQAJm3I5Dw4PKg8ODg8ODg4PDg8NDw4PDg8NDw8ODg8OKw4ODg8PDg0QDQ8ODw4ODg8ODw4rDg8ODg4PDg8NDw4PDg8NDw8qDw4PKg8rDisPKg4PDw4NLA4PDisOKw8qDysODg4sDgAJm3E6Dw4OKw8ODg8NDw8ODRAODg4PDg4PDg8ODQ8OLA0PDg8ODw4ODg8ODw0PDg8ODw0sDg8NDw4PDQ8ODw4PDg4ODw8qDw4OKw4sDisOKw8ODg8NLA4ODysOKw4rDysODg8rDgANBQAAAAAAAA==' 
###############################################################################
#                                                                             #
#                           S C R I P T S                                     #
#                                                                             #
###############################################################################   

#Não existem scripts para as automações acima referidas.

###############################################################################
#                                                                             #
#                           S E N S O R S                                     #
#                                                                             #
###############################################################################  

sensor:

  - platform: template
    sensors:
      tvsala:
        friendly_name: 'Tv da Sala'
        value_template: > 
         {%- if is_state('media_player.panasonic_viera_tv', 'off') -%}
            Desligada
         {%- else -%}
            Ligada
         {%- endif -%}


  
  
###############################################################################
#                                                                             #
#                           S W I T C H E S                                   #
#                                                                             #
###############################################################################  

switch:
  
#Switch Candeiro Sofá   

  - platform: mqtt
    name: "Candeiro Sofá"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    availability_topic: "tele/sonoff/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true    
    
  - platform: broadlink
    host: 192.168.1.100
    mac: '34:ea:34:58:8a:1d'
    
    

###############################################################################
#                                                                             #
#                           B I N A R Y   S E N S O R S                       #
#                                                                             #
###############################################################################   
 
binary_sensor:

  - platform: mqtt
    name: "Sonoff Candeiro Sofa"
    state_topic: "tele/sonoff/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
   

  - platform: device_tracker_sensor
    entities:
      - device_tracker.homecinema
      - device_tracker.tvsala
      - device_tracker.boxsala
      - device_tracker.broadlinksala
      
      
      
      
###############################################################################
#                                                                             #
#                           M E D I A  _ P L A Y E R                          #
#                                                                             #
###############################################################################   
       
media_player:

  - platform: mediaroom
    host: 192.168.1.64
    name: "Box Sala"
#    optimistic: True


  - platform: panasonic_viera
    host: 192.168.1.73
    
###############################################################################
#                                                                             #
#                           I M P R E S S O R A   3 D                         #
#                                                                             #
###############################################################################      
    
octoprint:
  host: 192.168.1.101
  api_key: !secret api_impressora3d
  bed: true
  number_of_tools: 1


    
###############################################################################
#                                                                             #
#                           G R O U P                                         #
#                                                                             #
###############################################################################     
  
group:
  
  sala:
    view: yes
    name: SALA
    entities:
      - group.salagroup

  salagroup:
    control: hidden
    name: Sala
    entities:
      - switch.candeiro_sofa
      - input_boolean.box_sala
